#!/bin/bash

if [ -f $HOME/.serverhostname ]
then
  SERVERHOSTNAME=`cat $HOME/.serverhostname`
else
  SERVERHOSTNAME=localhost
fi

CLIPBOARD=$HOME/.clipboardfromserver
scp $SERVERHOSTNAME:.clipboard $CLIPBOARD > /dev/null 2>&1
[ $? -eq 0 ] && xsel -bi < $CLIPBOARD && rm $CLIPBOARD
